FROM php:8.2.4RC1-apache-bullseye
RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /Munchy
COPY composer.json .

ENV COMPOSER_ALLOW_SUPERUSER=1

COPY --from=composer:2.4 /usr/bin/composer /usr/bin/composer

COPY ./composer.* .

RUN composer install --prefer-dist --no-dev --no-scripts --no-progress --no-interaction

# COPY ./Munchy .

#docker exec -it docker-php_app_1 sh

RUN composer dump-autoload --optimize